# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f415ac43178313dced24638d9e11d57591e30d3d8d1c89f0dcc4714cd16eac87bf71f0f325aabe60498f4ff412771d9afdd1be6429f064e116f980adc3645a14

test:
  secret_key_base: 29f983d81c694cfd9db796b36ef482dca3eece37c449a52b851b73f705120a2a983ff1d1b2365151e5d2113a5bbd147b61b8a0cc95480b2281d0535592dfaf03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
